export default [
  "Personal trainer",
  "Trainer",
  "Training",
  "Fitness",
  "Nutrition",
  "Coach",
  "Coaching",
  "Personal trainer atlanta",
  "Virtual personal trainer",
  "Personal trainer to lose weight",
  "Lgbt personal trainer",
  "Adhd personal trainer",
  "Trainerize personal trainer",
  "Online personal trainer",
  "Nutrition coach",
  "Personal trainer and nutrition coach",
  "Personal trainer 30326",
  "Mobile personal trainer",
  "In home personal trainer",
  "Remote personal trainer",
  "Personal trainer weight loss",
  "Affordable personal trainer"
];
